[project]
name = "nuu-dictate"
version = "0.1.0"
description = "Voice-to-text overlay MVP with hotkey activation"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pynput>=1.7.6",
    "pyaudio>=0.2.11",
    "pyautogui>=0.9.54",
    "openai>=1.0.0"
]
